spring:
  web:
    resources:
      static-locations: file:///C:/Users/Athang_y/Documents/CheckImages/
  application:
    name: ''
  datasource:
    url: jdbc:mysql://localhost:3306/eos_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: mail.eosglobe.com
    port: 587
    username: bi@eosglobe.com
    password: E0s@globe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.resource: TRACE
    org.springframework.mail: DEBUG
    org.apache.commons.mail: DEBUG
    javax.mail: DEBUG

project:
  image:
    check-image: C:/Users/Athang_y/Documents/CheckImages
  file:
    upload-dir: C:/Users/Athang_y/Desktop/AadharFileUpload
  pdf:
    save-path: C:/Users/Athang_y/Documents/LOIPdf
cors:
  allowed:
    origins:
      - http://localhost:5173

server:
  port: 8082