spring:
  application:
    name: ''
  datasource:
    url: jdbc:mysql://localhost:3306/eos_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: mail.eosglobe.com
    port: 587
    username: bi@eosglobe.com
    password: E0s@globe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

project:
  image: images/
  file:
    upload-dir: C:/Users/Bot_25/Desktop/Documents/AadharFileUpload

cors:
  allowed:
    origins:
      - http://localhost:5173

server:
  port: 8082
